### ISSUE TITLE
Installation / running instructions

### ISSUE THREAD

**Issue by petigura** [jvanzand/trends#1]
Hey, @jvanzand. When you get a moment, can you include installation instructions and a one line script that can generate the 191939 plot.

**Comment by jvanzand** [comment]
Ok I included some directions. I have a (multi-line) script to generate the plot, but I can add a one-line script that points to the first one if needed.

**Comment by petigura** [comment]
Code is missing dependencies. Learn how these are specified for python repos. 


```
[trends]$ python analysis/hd191939_plot.py 
Traceback (most recent call last):
  File "/Users/petigura/code/trends/analysis/hd191939_plot.py", line 3, in <module>
    import helper_functions as hlp
  File "/Users/petigura/code/trends/analysis/helper_functions.py", line 7, in <module>
    from c_kepler import _kepler as ck
ImportError: cannot import name '_kepler' from 'c_kepler' (unknown location)
```

**Comment by jvanzand** [comment]
This still needs one task: remove radvel from requirements because it can't be installed with conda. Then tell users to conda install requirements.txt and pip install only radvel separately.
