### ISSUE TITLE
cannot get code up and running following readme

### ISSUE THREAD

**Issue by petigura** [jvanzand/trends#16]
![image](https://user-images.githubusercontent.com/694371/144148995-8218cf1a-38f1-4820-8304-5342f1bffe1c.png)

**Comment by jvanzand** [comment]
I see that the environment is called 'trends'. Was it created using the current environment.yml file (which should create an environment called 'trends_env')? environment.yml should install tqdm in the new environment:
<img width="308" alt="Screen Shot 2021-12-02 at 12 05 22 PM" src="https://user-images.githubusercontent.com/58751015/144495172-4be4ebd2-fb16-461b-ae9d-b4b927b7a6ad.png">

**Comment by petigura** [comment]
got it working with fresh conda env
